"""Semantic fixture invariants shared by serverless smoke checks and live evidence."""


def integrity_queries(c):
    return {
        "missing_coil": f"SELECT count(*) n FROM {c}.gold.claims_history c LEFT ANTI JOIN {c}.silver.heats_coils m USING(coil_id)",
        "missing_mtc": f"SELECT count(*) n FROM {c}.silver.heats_coils m LEFT ANTI JOIN {c}.silver.mill_test_certs t USING(coil_id)",
        "missing_customer": f"SELECT count(*) n FROM {c}.gold.claims_history c LEFT ANTI JOIN {c}.silver.customers d USING(customer_id)",
        "missing_supplier": f"SELECT count(*) n FROM {c}.silver.heats_coils m LEFT ANTI JOIN {c}.silver.suppliers s ON m.coating_supplier_id=s.supplier_id",
        "missing_raw_supplier": f"SELECT count(*) n FROM {c}.silver.heats_coils m LEFT ANTI JOIN {c}.silver.suppliers s ON m.raw_material_supplier_id=s.supplier_id",
        "missing_defect": f"SELECT count(*) n FROM {c}.gold.claims_history c LEFT ANTI JOIN {c}.silver.defect_codes d USING(defect_code)",
        "missing_adjudication": f"SELECT count(*) n FROM {c}.gold.claims_history c LEFT ANTI JOIN {c}.gold.adjudications_history a USING(claim_id)",
        "warranty_version_mismatch": f"SELECT count(*) n FROM {c}.gold.claims_history c LEFT JOIN {c}.silver.coating_warranty_terms w ON c.warranty_id=w.warranty_id AND w.section_ref='coverage' WHERE w.warranty_id IS NULL OR NOT(c.ship_date >= w.effective_from AND c.ship_date < w.effective_to AND c.product_line=w.product_line AND c.coating_class=w.coating_class AND c.region=w.region)",
        "invalid_duplicate": f"SELECT count(*) n FROM {c}.gold.claims_history d LEFT JOIN {c}.gold.claims_history o ON d.duplicate_of_claim_id=o.claim_id WHERE d.ground_truth_label='duplicate' AND (o.claim_id IS NULL OR NOT(d.coil_id=o.coil_id AND d.customer_id=o.customer_id AND d.defect_code=o.defect_code AND d.claimed_amount=o.claimed_amount AND d.claimed_tonnage=o.claimed_tonnage AND d.defect_narrative=o.defect_narrative AND datediff(d.claim_date,o.claim_date) BETWEEN 0 AND 7))",
        "in_spec_not_conforming": f"SELECT count(*) n FROM {c}.gold.claims_history c JOIN {c}.silver.mill_test_certs m USING(coil_id) JOIN {c}.silver.spec_standards s ON c.spec_id=s.spec_id AND s.section_ref='mechanical' WHERE c.ground_truth_label='in_spec_should_deny' AND NOT(m.tensile_mpa BETWEEN s.structured_params.mechanical.tensile_mpa.min AND s.structured_params.mechanical.tensile_mpa.max AND m.yield_mpa BETWEEN s.structured_params.mechanical.yield_mpa.min AND s.structured_params.mechanical.yield_mpa.max AND m.elongation_pct BETWEEN s.structured_params.mechanical.elongation_pct.min AND s.structured_params.mechanical.elongation_pct.max AND m.carbon_pct BETWEEN s.structured_params.chemistry.carbon_pct.min AND s.structured_params.chemistry.carbon_pct.max AND m.manganese_pct BETWEEN s.structured_params.chemistry.manganese_pct.min AND s.structured_params.chemistry.manganese_pct.max)",
        "exclusion_not_present": f"SELECT count(*) n FROM {c}.gold.claims_history c JOIN {c}.silver.coating_warranty_terms w ON c.warranty_id=w.warranty_id AND w.section_ref='coverage' WHERE c.ground_truth_label='out_of_warranty_or_environment_excluded' AND NOT(months_between(c.claim_date,c.ship_date)>w.structured_params.duration_months OR array_contains(w.structured_params.excluded_environments,c.environment) OR array_contains(w.structured_params.excluded_installations,c.installation) OR c.coast_distance_km<w.structured_params.min_coast_distance_km)",
        "over_claim_not_partial": f"SELECT count(*) n FROM {c}.gold.claims_history c JOIN {c}.gold.adjudications_history a USING(claim_id) WHERE c.ground_truth_label='over_claim' AND NOT(c.claimed_tonnage>c.shipped_tonnage AND c.claimed_freight>c.freight_cap AND a.approved_amount<c.claimed_amount AND a.approved_amount=cast(c.shipped_tonnage*c.unit_price+c.freight_cap as decimal(18,2)))",
        "supplier_not_traceable": f"SELECT count(*) n FROM {c}.gold.claims_history c JOIN {c}.silver.heats_coils m USING(coil_id) JOIN {c}.silver.mill_test_certs t USING(coil_id) JOIN {c}.gold.adjudications_history a USING(claim_id) WHERE c.ground_truth_label='supplier_attributable' AND NOT(a.supplier_attributable AND a.recovery_supplier_id=m.coating_supplier_id AND NOT t.coating_adhesion_pass)",
        "invalid_money": f"SELECT count(*) n FROM {c}.gold.adjudications_history WHERE approved_amount<0 OR approved_amount>claimed_amount OR (verdict<>'APPROVE' AND (approved_amount<>0 OR disposition IS NOT NULL))",
    }
