-- Render ${catalog} from settings.yaml with run.py govern. No secrets.
-- Account groups adjuster / metallurgy_analyst are provisioned by run.py.
-- No users are enrolled automatically. Admins retain engineering visibility.
CREATE SCHEMA IF NOT EXISTS `${catalog}`.bronze;
CREATE SCHEMA IF NOT EXISTS `${catalog}`.silver;
CREATE SCHEMA IF NOT EXISTS `${catalog}`.gold;
CREATE OR REPLACE FUNCTION `${catalog}`.silver.mask_customer(value STRING) RETURNS STRING RETURN CASE WHEN is_account_group_member('adjuster') OR is_member('admins') THEN value ELSE concat('REDACTED-', sha2(value, 256)) END;
CREATE OR REPLACE FUNCTION `${catalog}`.silver.mask_money(value DECIMAL(18,2)) RETURNS DECIMAL(18,2) RETURN CASE WHEN is_account_group_member('adjuster') OR is_member('admins') THEN value ELSE CAST(NULL AS DECIMAL(18,2)) END;
GRANT USE CATALOG ON CATALOG `${catalog}` TO `adjuster`;
GRANT USE SCHEMA ON SCHEMA `${catalog}`.silver TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.spec_standards TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.coating_warranty_terms TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.customers TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.suppliers TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.defect_codes TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.heats_coils TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.mill_test_certs TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.claims_history TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.silver.adjudications_history TO `adjuster`;
GRANT USE SCHEMA ON SCHEMA `${catalog}`.gold TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.gold.claims_history TO `adjuster`;
GRANT SELECT ON TABLE `${catalog}`.gold.adjudications_history TO `adjuster`;
GRANT USE CATALOG ON CATALOG `${catalog}` TO `metallurgy_analyst`;
GRANT USE SCHEMA ON SCHEMA `${catalog}`.silver TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.spec_standards TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.coating_warranty_terms TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.customers TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.suppliers TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.defect_codes TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.heats_coils TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.mill_test_certs TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.claims_history TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.silver.adjudications_history TO `metallurgy_analyst`;
GRANT USE SCHEMA ON SCHEMA `${catalog}`.gold TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.gold.claims_history TO `metallurgy_analyst`;
GRANT SELECT ON TABLE `${catalog}`.gold.adjudications_history TO `metallurgy_analyst`;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.customers ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.customers ALTER COLUMN customer_name SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.customers ALTER COLUMN email SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.heats_coils ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.heats_coils ALTER COLUMN unit_price SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.claims_history ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.claims_history ALTER COLUMN unit_price SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.claims_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.claims_history ALTER COLUMN claimed_freight SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.claims_history ALTER COLUMN freight_cap SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.adjudications_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.bronze.adjudications_history ALTER COLUMN approved_amount SET MASK `${catalog}`.silver.mask_money;
ALTER TABLE `${catalog}`.silver.customers ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER TABLE `${catalog}`.silver.customers ALTER COLUMN customer_name SET MASK `${catalog}`.silver.mask_customer;
ALTER TABLE `${catalog}`.silver.customers ALTER COLUMN email SET MASK `${catalog}`.silver.mask_customer;
ALTER TABLE `${catalog}`.silver.heats_coils ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER TABLE `${catalog}`.silver.heats_coils ALTER COLUMN unit_price SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.claims_history ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.silver.claims_history ALTER COLUMN unit_price SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.claims_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.claims_history ALTER COLUMN claimed_freight SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.claims_history ALTER COLUMN freight_cap SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.adjudications_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.silver.adjudications_history ALTER COLUMN approved_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.claims_history ALTER COLUMN customer_id SET MASK `${catalog}`.silver.mask_customer;
ALTER MATERIALIZED VIEW `${catalog}`.gold.claims_history ALTER COLUMN unit_price SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.claims_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.claims_history ALTER COLUMN claimed_freight SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.claims_history ALTER COLUMN freight_cap SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.adjudications_history ALTER COLUMN claimed_amount SET MASK `${catalog}`.silver.mask_money;
ALTER MATERIALIZED VIEW `${catalog}`.gold.adjudications_history ALTER COLUMN approved_amount SET MASK `${catalog}`.silver.mask_money;
-- FUTURE COMPONENTS: app/agent service-principal placeholders; replace IDs before enabling.
-- GRANT USE CATALOG ON CATALOG `${catalog}` TO `<app-service-principal-application-id>`;
-- GRANT USE SCHEMA ON SCHEMA `${catalog}`.gold TO `<app-service-principal-application-id>`;
-- GRANT SELECT ON TABLE `${catalog}`.gold.claims_history TO `<app-service-principal-application-id>`;
-- GRANT USE CATALOG ON CATALOG `${catalog}` TO `<agent-service-principal-application-id>`;
-- GRANT USE SCHEMA ON SCHEMA `${catalog}`.silver TO `<agent-service-principal-application-id>`;
-- GRANT SELECT ON TABLE `${catalog}`.silver.spec_standards TO `<agent-service-principal-application-id>`;
-- GRANT SELECT ON TABLE `${catalog}`.silver.coating_warranty_terms TO `<agent-service-principal-application-id>`;
-- SP unmasking entitlement is intentionally deferred; do not add SPs to human roles.
